// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddingCourseDialog: typeof import('./src/components/CourseAdmin/Dialogs/AddingCourseDialog.vue')['default']
    ClickCourseInfoDialog: typeof import('./src/components/CoursePlanAdmin/Dialogs/ClickCourseInfoDialog.vue')['default']
    ClickCoursePlanDialog: typeof import('./src/components/CoursePlanAdmin/Dialogs/ClickCoursePlanDialog.vue')['default']
    CourseAdmin: typeof import('./src/components/CourseAdmin/CourseAdmin.vue')['default']
    CoursePlanAdmin: typeof import('./src/components/CoursePlanAdmin/CoursePlanAdmin.vue')['default']
    CoursePlanTable: typeof import('./src/components/CoursePlanAdmin/CoursePlanTable.vue')['default']
    DeletingCourseDialog: typeof import('./src/components/CourseAdmin/Dialogs/DeletingCourseDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCascaderPanel: typeof import('element-plus/es')['ElCascaderPanel']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTransfer: typeof import('element-plus/es')['ElTransfer']
    FunctionButtonArea: typeof import('./src/components/CourseAdmin/FunctionButtonArea.vue')['default']
    GradeSelector: typeof import('./src/components/CourseAdmin/GradeSelector.vue')['default']
    GradeSelectorBar: typeof import('./src/components/CoursePlanAdmin/GradeSelectorBar.vue')['default']
    GroupSelector: typeof import('./src/components/GroupSelector.vue')['default']
    LoadingMask: typeof import('./src/components/loadingMask.vue')['default']
    OtherAdmin: typeof import('./src/components/OtherAdmin/OtherAdmin.vue')['default']
    SelectPlanDialog: typeof import('./src/components/CourseAdmin/Dialogs/SelectPlanDialog.vue')['default']
    SemesterSelector: typeof import('./src/components/SemesterSelector.vue')['default']
    TimetableBlock: typeof import('./src/components/CourseAdmin/WeeklyTimetable/TimetableBlock.vue')['default']
    TopMenu: typeof import('./src/components/TopMenu.vue')['default']
    WeeklyTimetable: typeof import('./src/components/CourseAdmin/WeeklyTimetable/WeeklyTimetable.vue')['default']
    WeekSelectBar: typeof import('./src/components/CourseAdmin/WeekSelectBar.vue')['default']
  }
}

export { }
