// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CourseAdmin: typeof import('./src/components/CourseAdmin/CourseAdmin.vue')['default']
    CourseAdminBody: typeof import('./src/components/CourseAdmin/CourseAdminBody.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTransfer: typeof import('element-plus/es')['ElTransfer']
    FunctionButtonArea: typeof import('./src/components/CourseAdmin/FunctionButtonArea.vue')['default']
    LoadingMask: typeof import('./src/components/loadingMask.vue')['default']
    TimetableBlock: typeof import('./src/components/CourseAdmin/WeeklyTimetable/TimetableBlock.vue')['default']
    WeeklyTimetable: typeof import('./src/components/CourseAdmin/WeeklyTimetable/WeeklyTimetable.vue')['default']
    WeekSelectBar: typeof import('./src/components/CourseAdmin/WeekSelectBar.vue')['default']
  }
}

export { }
