// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddingCourseDialog: typeof import('./src/components/CourseAdmin/Dialogs/AddingCourseDialog.vue')['default']
    ClickCourseInfoDialog: typeof import('./src/components/CoursePlanAdmin/Dialogs/ClickCourseInfoDialog.vue')['default']
    ClickCoursePlanDialog: typeof import('./src/components/CoursePlanAdmin/Dialogs/ClickCoursePlanDialog.vue')['default']
    ClickWeeklyHoursDialog: typeof import('./src/components/CoursePlanAdmin/Dialogs/ClickWeeklyHoursDialog.vue')['default']
    CourseAdmin: typeof import('./src/components/CourseAdmin/CourseAdmin.vue')['default']
    CourseCard: typeof import('./src/components/CourseCard.vue')['default']
    CoursePlanAdmin: typeof import('./src/components/CoursePlanAdmin/CoursePlanAdmin.vue')['default']
    CoursePlanTable: typeof import('./src/components/CoursePlanAdmin/CoursePlanTable.vue')['default']
    DeletingCourseDialog: typeof import('./src/components/CourseAdmin/Dialogs/DeletingCourseDialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCascaderPanel: typeof import('element-plus/es')['ElCascaderPanel']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FunctionButtonArea: typeof import('./src/components/CourseAdmin/FunctionButtonArea.vue')['default']
    GroupSelector: typeof import('./src/components/GroupSelector.vue')['default']
    LazyWeekSelectBar: typeof import('./src/components/CourseAdmin/LazyWeekSelectBar.vue')['default']
    LoadingMask: typeof import('./src/components/loadingMask.vue')['default']
    OtherAdmin: typeof import('./src/components/OtherAdmin/OtherAdmin.vue')['default']
    PageTopAlerts: typeof import('./src/components/PageTopAlerts.vue')['default']
    SelectPlanDialog: typeof import('./src/components/CourseAdmin/Dialogs/SelectPlanDialog.vue')['default']
    TimetableBlock: typeof import('./src/components/CourseAdmin/WeeklyTimetable/TimetableBlock.vue')['default']
    TimetableBlockDetailDialog: typeof import('./src/components/CourseAdmin/Dialogs/TimetableBlockDetailDialog.vue')['default']
    TopMenu: typeof import('./src/components/TopMenu.vue')['default']
    WeeklyTimetable: typeof import('./src/components/CourseAdmin/WeeklyTimetable/WeeklyTimetable.vue')['default']
  }
}

export { }
